global using System.Collections.Immutable;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using UnDns.Models;
global using UnDns.Presentation;
global using UnDns.DataContracts;
global using UnDns.DataContracts.Serialization;
global using UnDns.Services.Caching;
global using UnDns.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
